ci: automate ARN publishing
elastic/apm-aws-lambda pull request #101
Opened 2022-01-13 11:14 UTC by v1v

### What

Publish the AWS lambda as an ARN for AWS users in various regions for `linux` and `arm`.

### Actions

- [ ] Login to AWS. **status**: Waiting for the new AWS account.
- [ ] List of Regions where to publish. **status**: Is it possible to list this dynamically?
- [ ] Make publish to the above given regions and store the ARN to be consumed. **status**: to be implemented
- [ ] Create Release Notes. **status**: to be implemented
- [ ] Enable only for the tag releases. **status**: uncomment the code in the CI

2022-01-13 11:28 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-101/detail/PR-101/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-101/detail/PR-101/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-101/detail/PR-101/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-101/detail/PR-101/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-aws-lambda_101.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-01-13T11:04:46.961Z&rangeTo=2022-01-13T11:24:46.961Z&transactionName=library%2Fapm-aws-lambda-mbp%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=b23eb17c953b09989a37907dd1a78f65&transactionId=0558f3e2e3b16fdd)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-01-13T11:14:46.961+0000


* Duration: 14 min 33 sec


* Commit: e27ca6442e1ee803555d7cb4767b1289701cd2e4



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 78  |
| Skipped      | 0 |
| Total        | 78   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-01-13 15:02 UTC, v1v commented
/test

2022-01-13 17:16 UTC, v1v commented on apm-lambda-extension/Makefile
> +		--generate-cli-skeleton > $(AWS_FOLDER)/${AWS_DEFAULT_REGION}
`--generate-cli-skeleton` will do nothing -> dry-run for now

2022-01-13 17:17 UTC, v1v commented on .ci/Jenkinsfile
> +                unstash "arn-amd"
This is the trick to converge the outcome from the publishing stage for the two supported architectures (ARM and AMD64)

2022-01-13 21:30 UTC, v1v commented on apm-lambda-extension/Makefile
> +build-and-publish: validate-layer-name validate-aws-default-region
`validate-*` are the goals to avoid duplication of missing arguments/env-variables in some other Make goals

2022-01-13 21:31 UTC, v1v commented on apm-lambda-extension/Makefile
> +		--generate-notes \
Automatically generate title and notes for the release, it works in conjunction with `--notes-file`

2022-01-13 21:53 UTC, v1v commented on apm-lambda-extension/Makefile
> +		--repo v1v/apm-aws-lambda
Create releases in the forked repo for testing purposes

2022-01-26 18:48 UTC, astorm requested changes
Things look good on the publishing a list of ARNs front, so +1 there (although the jenkins build syntax isn't something I'm as familiar with, so I can't comment in depth on that)

One problem I noticed is the changes to the `Makefile` appear to break the user-facing installer.  If you look at [this docs section](https://www.elastic.co/guide/en/apm/guide/current/aws-lambda-extension.html#aws-lambda-install) you can see users have the self-service option of installing the extension by running a small Node.js command line program.  

When running the program on the `main` branch, it successfully builds and installs the Lambda extension (as expected). However, when we attempt to run it with this PR branch, it fails half way through with the following error.

```
$ AWS_DEFAULT_REGION=... AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=... ./elastic-lambda.js install
//...
# building extension and publishing as layer
stdout: running cd .. && make build-and-publish
error: Command failed: cd .. && make build-and-publish
Makefile:81: *** BRANCH_NAME is undefined.  Stop.
make: *** [build-and-publish] Error 2
```

I don't have any strong opinions on how we achieve this, but users being able to self serve by running this program is an important part of the this product.  

Can we ensure that this functionality remains in place?

2022-01-26 19:09 UTC, v1v commented on apm-lambda-extension/Makefile
> +publish: validate-branch-name validate-layer-name validate-aws-default-region
This should avoid the breaking change with the `BRANCH_NAME` validation, somehow, I added this validation when it should not be added in this particular goal as it's not consumed

```suggestion
publish: validate-layer-name validate-aws-default-region
```

2022-01-27 17:44 UTC, astorm commented
@v1v Looks like we cleared up the previous errors here -- huzzah!

However, I'm now seeing a _new_ error when running the installer -- specifically

```
% AWS_DEFAULT_REGION=... AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=... ./elastic-lambda.js install

/* ... */

# building extension and publishing as layer
error: Command failed: /path/to/apm-aws-lambda/apm-lambda-extension/cli/elastic-lambda.js build-and-publish
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getLastJsonFromShellOutput (/path/to/apm-aws-lambda/apm-lambda-extension/cli/build-and-publish.js:37:23)
    at /path/to/apm-aws-lambda/apm-lambda-extension/cli/build-and-publish.js:57:22
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)

stderr: undefined:1

/* ... */

encountered error, exiting

% echo $?
1
```

I believe this is result of our changing the invocation of the `publish-layer-version` such that it no longer outputs to stdout, and instead outputs to a file

https://github.com/elastic/apm-aws-lambda/pull/101/files#diff-a402b77bda476fe59d07fb66cd01a490fb31ef84f423783e2bd7799a5db9596dR61-R68

The `./elastic-lambda.js install` command processes the stdout results of `publish-layer-version` looking for a JSON string.  With the new `Makefile` this string ends up in a file instead of stdout.  The installer doesn't see the JSON, tries to process a blank string as a JSON string, and then exits with an error when it can't (since, without the information in this file, it can't proceed)

I'm unsure what the intent of this change is, but if I was trying to fix this I'd replace with the redirect (`>`) with a `|` into `tee`

```
	@aws lambda \
		--output json \
		publish-layer-version \
		--layer-name "${ELASTIC_LAYER_NAME}" \
		--description "AWS Lambda Extension Layer for Elastic APM" \
		--license "Apache-2.0" \
		--compatible-architectures "$(ARCHITECTURE)" \
		--zip-file "fileb://./bin/extension.zip"  | tee $(AWS_FOLDER)/${AWS_DEFAULT_REGION}
```		

Assuming `tee` is available in our build environment, this should maintain the preexisting behavior of outputting to stdout (allowing the installer to read that JSON), while also writing the results out to the `$(AWS_FOLDER)/${AWS_DEFAULT_REGION}` file.

2022-01-27 20:12 UTC, v1v commented
Thanks @astorm for your review! https://github.com/elastic/apm-aws-lambda/pull/101/commits/1b1d08e43e0e3f16074103cad68493a7bdf0f84e should now provide the compatibility with the existing process in addition to the new proposed here. No more breaking changes! Thanks again

2022-01-27 20:14 UTC, v1v commented on apm-lambda-extension/Makefile
> +publish: validate-layer-name validate-aws-default-region
This goal is uses in two different places:
- The traditional one when using `./elastic-lambda.js install`
- The one to rollout the ARN in all the AWS regions, see `publish-in-all-aws-regions`

I decided to refactor `build-and-publish` in favour of avoiding running `aws lambda` command in two different Make goals.

2022-02-01 23:08 UTC, astorm approved these changes
Thanks for making those changes @v1v -- `./elastic-lambda.js build-and-publish` appears to be doing its thing again 👍

2022-02-02 09:33 UTC, merged