Support Lambda Platform Metrics
elastic/apm-aws-lambda pull request #202
Opened 2022-05-31 18:27 UTC by jlvoiseux

### Motivation / Summary
This PR is the continuation of #127, which had become obsolete and non-digestible due to the many changes brought to the extension since the initialization of the PR. It resolves #109.

The general flow is as follows:
- The extension gets started (cold start)
- A metadata container is initialized. This container is populated with the metadata extracted from the first APM payload sent by the agent
- The log processing goroutine now handles a new type of `SubEventType` alongside `RuntimeDone`: `Report`. This report contains the metrics that we want to send to the APM Server. These metrics are packaged inside an APM payload (alongside the extracted metadata) in a dedicated function.

### Files / Added Elements
- 944e71ffca910c8951dfa07b1b507520407edf53 : Add a new package `model` which is a partial reproduction of the data model used by the [Go APM Agent](https://github.com/elastic/apm-agent-go/blob/main/model/model.go)
- 1ec30ab1bbf383949b8084bfa5a1ae0089f7747d : Add a version utility file that is used to populate metadata
- 10e2c77dc8b3af3325fc58058be22c86c1d7ff66 and 3ec3bf9f4c9968c42113593ff91a484f0a4b9e29 : Functions that extract metadata from a given APM payload and populate a dedicated container. Since metadata extraction is tied to APM data, it is part of the `extension` package. Metadata is only extracted from the first APM payload received during the current lifetime of the extension.
- a515a6d456b3600bd1cc8c288c183b82ae2f88e3 and c2b056a07d6666ac300fa8303d1945c9cbae5700 : Functions that turn the platform report provided by the Lambda runtime into a payload to be sent to the APM Server. Since metrics extraction is tied to logs data, it is part of the `logsapi` package.
- 2b651c8d239bc930125bbaf6653336c1406035f2 and 614be84d8f0930c36d73a6d813fb8f745eab7ace : `main` updates to modify the goroutines in order to extract metadata and process metrics.

### Limitations / Elements to discuss
- After several tests with [two](https://github.com/aws-samples/aws-lambda-extensions/tree/main/go-example-logs-api-extension) [sample](https://github.com/aws-samples/aws-lambda-extensions/tree/main/s3-logs-extension-demo-zip-archive) extensions with two different logs processing philosophies, we can [conclude](https://github.com/aws-samples/aws-lambda-extensions/blob/949b01bd789f90bd39cc718fc11935c4109dfcf7/s3-logs-extension-demo-zip-archive/extensionssrc/extensions/logs_api_http_extension.py#L29) that the metrics report corresponding to the invocation `i` will be received during the execution of the invocation `i+1`.
- The current implementation changes the Agent name to `apm-lambda-extension` when the metadata is attached to the generated metrics. While this makes sense in the framework of observability, the current APM UI is not equipped accordingly, and the service is associated to an unknown runtime:
![image](https://user-images.githubusercontent.com/48380853/171245536-c16a4b46-a0f9-43cf-8e53-232ffda28675.png)
My suggestion would be to stop altering the metadata for now to provide a consistent experience to end users.
- The current package architecture can also be discussed. I wished I was able to keep `logsapi` and `extension` completely separate, but in the current implementation, `logsapi.ProcessLogs()` takes an `apmServerTransport` in argument in order to enqueue APM metrics payloads.
- Several `faas` fields will be added to the `metricset` object in the APM data model (PR to be created). The subsequent modifications are beyond the scope of this initial PR, which aims to provide an initial implementation of Lambda metrics generation. 

### How to test
- Clone the extension repo
- Follow the instructions presented in the following sample repo
- After executing your sample Lambda function a few times, you should see documents corresponding to your Lambda Platform report in your Elastic Cloud instance:
```
// Lambda Report
REPORT RequestId: 6862dc9b-3266-470a-9979-f39c21164f8c	Duration: 94.65 ms	Billed Duration: 95 ms	Memory Size: 128 MB	Max Memory Used: 77 MB	Init Duration: 479.30 ms	
```
![image](https://user-images.githubusercontent.com/48380853/171257553-ae3b0d95-c15b-4f50-8542-9567d57bcaa3.png)
![image](https://user-images.githubusercontent.com/48380853/171257771-9e6e2130-f200-4698-8a50-0e4234e93179.png)

2022-05-31 18:32 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-202/detail/PR-202/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-202/detail/PR-202/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-202/detail/PR-202/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-202/detail/PR-202/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-aws-lambda_202.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-05-31T18:17:59.551Z&rangeTo=2022-05-31T18:37:59.551Z&transactionName=BUILD+library%2Fapm-aws-lambda-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=935011357e61bf99501bbd9d85c4f54a&transactionId=8755f1205a950395)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-05-31T18:27:59.551+0000


* Duration: 4 min 0 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-202/detail/PR-202/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `lint-run`
<ul>
<li>Took 1 min 43 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/library/pipelines/apm-aws-lambda-mbp/pipelines/PR-202/runs/1/steps/112/log/?start=0">here</a></li>
<li>Description: <code>make lint</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-06-02 04:57 UTC, axw requested changes
Generally looks good, mostly minor comments.

2022-06-02 04:57 UTC, axw commented on apm-lambda-extension/logsapi/process_metrics_test.go
> +	mc.Metadata.System = model.System{}
```suggestion
```

Aren't they already zero valued?

2022-06-02 10:28 UTC, felixbarny commented on apm-lambda-extension/logsapi/process_metrics.go
> +	}
> we should probably defer modifying the agent name for now anyway

that makes sense to me

2022-06-02 13:42 UTC, jlvoiseux commented on apm-lambda-extension/extension/process_metadata_test.go
> +	}
Fixed in 11e874b

2022-06-02 13:43 UTC, jlvoiseux commented on apm-lambda-extension/logsapi/process_metrics_test.go
> +	"gotest.tools/assert"
Indeed, great catch! Fixed in 11e874b

2022-06-02 13:45 UTC, jlvoiseux commented on apm-lambda-extension/logsapi/process_metrics_test.go
> +	assert.Equal(t, string(requestBytes), desiredOutput)
Fixed in 11e874b

2022-06-02 13:45 UTC, jlvoiseux commented on apm-lambda-extension/logsapi/process_metrics_test.go
> +	}
Fixed in 11e874b

2022-06-02 13:46 UTC, jlvoiseux commented on apm-lambda-extension/logsapi/process_metrics_test.go
> +	mc.Metadata.System = model.System{}
Fixed in 11e874b

2022-06-03 15:34 UTC, jlvoiseux commented on apm-lambda-extension/logsapi/process_metrics.go
> +	metricsContainer.Add("aws.lambda.metrics.UsedMemory", nil, float64(platformReportMetrics.MaxMemoryUsedMB)*convMB2Bytes) // Unit : Bytes
Fixed in c018cb6

2022-06-03 15:34 UTC, jlvoiseux commented on apm-lambda-extension/logsapi/process_metrics.go
> +func (mc MetricsContainer) Add(name string, labels []model.MetricLabel, value float64) {
Fixed in c018cb6

2022-06-03 15:35 UTC, jlvoiseux commented on apm-lambda-extension/logsapi/process_metrics.go
> +	}
Fixed in c018cb6

2022-06-03 15:40 UTC, jlvoiseux commented on apm-lambda-extension/logsapi/process_metrics.go
> +	metricsContainer.Add("aws.lambda.metrics.Timeout", nil, math.Ceil(float64(functionData.DeadlineMs-functionData.Timestamp.UnixMilli())/1e3)*1e3) // Unit : Milliseconds
While the Timeout was not part of the initial specification, I believe that sending in to ES (and Kibana) is useful for visualisation purpose. If they have access to this metric, end-users can build a dashboard that would help them decide whether or not the timeout they specified for their Lambda functions is adequate, given execution time measurements.

2022-06-03 15:44 UTC, jlvoiseux commented on apm-lambda-extension/logsapi/process_metrics.go
> +	metricsContainer.Add("aws.lambda.metrics.ColdStartDuration", nil, float64(platformReportMetrics.InitDurationMs))        // Unit : Milliseconds
Corrected in d5952d6

2022-06-03 15:49 UTC, jlvoiseux commented on apm-lambda-extension/extension/process_metadata.go
> +	for {
The loop was replaced by a single scanner iteration in 62501a6

2022-06-07 03:39 UTC, axw commented on apm-lambda-extension/go.mod
> +	go.elastic.co/apm v1.15.0
We should use `go.elastic.co/apm/v2`, the current major version.

2022-06-07 03:39 UTC, axw commented on apm-lambda-extension/logsapi/process_metrics.go
> +	metricsContainer.Add("aws.lambda.metrics.Timeout", nil, math.Ceil(float64(functionData.DeadlineMs-functionData.Timestamp.UnixMilli())/1e3)*1e3) // Unit : Milliseconds
Sounds good, thanks.

2022-06-07 03:44 UTC, axw approved these changes
LGTM, just one thing (we should use Go agent v2).

I assume we'll want the labels to be recorded as `faas.*`, rather than `labels.faas_*`, right? Is your plan that once the server is updated, we'll come back and update the Go agent's model and the extension to send them as metricset fields? Similar to what we do for transaction and span properties: https://github.com/elastic/apm-agent-go/blob/94d06659448a555142c087721a79fff3ee732b49/model/model.go#L798-L804

2022-06-07 15:41 UTC, jlvoiseux commented
@axw Thank you for the review. I have updated the model to `v2`.
You are absolutely right regarding the `faas` labels. There was nothing preventing us from modifying the APM model in parallel to this PR, but given the number of changes introduced, I thought that the added complexity of having to test the PR alongside a modified APM Model was going to be too much at once. However, that is definitely the next step once we merge this.

2022-06-08 08:19 UTC, merged