Added Secret Manager support
elastic/apm-aws-lambda pull request #208
Opened 2022-06-03 09:05 UTC by AlexanderWert

Closes #105
Closes #206

## Steps for end to end testing:

### Step 1: Create a secret in the AWS Secret Manager.
- The secret must be in the same AWS region as the target lambda function
- Create the secret either for the APM secret token OR the APM API key
- The secret type **must be** `Plain Text`
- Optionally, you can select a custom KMS key for encryption (Note: in this case you will need additional key permissions on your Lambda functions)
  - Otherwise: use the key provided by AWS: `aws/secretsmanager` (No additional key permissions needed for this)
  
<img width="930" alt="image" src="https://user-images.githubusercontent.com/866830/171822657-e6a4d2b7-99a1-440f-87d1-888d7b48ba16.png">

### Step 2: Create and setup the Lambda function
- Follow [these docs](https://www.elastic.co/guide/en/apm/guide/8.2/monitoring-aws-lambda.html) for general setup of the Lambda function with Elastic APM
- However, create and use a custom extension layer based on this PR
- In the environment variables configuration **instead** of providing the `ELASTIC_APM_SECRET_TOKEN` or `ELASTIC_APM_API_KEY` specify the `ELASTIC_APM_SECRET_MANAGER_SECRET_TOKEN_ID` or `ELASTIC_APM_SECRET_MANAGER_API_KEY_ID` variables. Use the `secret-name` as the value.

### Step 3: Add permissions
- Under `Configuration` > `Permissions` > `Execution Role` click on the execution role to edit the permissions
- Add a new inline policy with the following JSON-based permission definition:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": [
                "HERE_GOES_THE_ARN_OF_THE_SECRET"
            ]
        },
        // The following is only needed if a custom key is used
        {
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt"
            ],
            "Resource": [
                "HERE_GOES_THE_ARN_OF_THE_CUSTOM_KEY"
            ]
        }
    ]
}
```

### Step 4: Invoke the lambda function and validate data in Elastic APM UI

2022-06-03 09:14 UTC, apmmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-208/detail/PR-208/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-208/detail/PR-208/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-208/detail/PR-208/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-208/detail/PR-208/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-aws-lambda_208.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-06-03T08:55:36.986Z&rangeTo=2022-06-03T09:15:36.986Z&transactionName=BUILD+library%2Fapm-aws-lambda-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=93f47ff63f01d20ed02930290fa887db&transactionId=3bc24c09c4226301)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-06-03T09:05:36.986+0000


* Duration: 9 min 6 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 188  |
| Skipped      | 4 |
| Total        | 193   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-208/detail/PR-208/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Test / Matrix - PLATFORM = 'macosx && x86_64', GO_VERSION = '1.18' / Test / Test_handleIntakeV2EventsNoQueryParam – elastic/apm-lambda-extension/extension`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   Test_handleIntakeV2EventsNoQueryParam
panic: Fail in goroutine after Test_handleIntakeV2EventsQueryParam has completed

goroutine 129 [running]:
testing.(*common).Fail(0xc000112b60)
	/var/lib/jenkins/workspace/ibrary_apm-aws-lambda-mbp_PR-208/.gvm/versions/go1.18.darwin.amd64/src/testing/testing.go:817 +0xe5
elastic/apm-lambda-extension/extension.Test_handleIntakeV2EventsQueryParam.func2()
	/private/var/lib/jenkins/workspace/ibrary_apm-aws-lambda-mbp_PR-208/src/github.com/elastic/apm-aws-lambda/apm-lambda-extension/extension/http_server_test.go:242 +0xd2
created by elastic/apm-lambda-extension/extension.Test_handleIntakeV2EventsQueryParam
	/private/var/lib/jenkins/workspace/ibrary_apm-aws-lambda-mbp_PR-208/src/github.com/elastic/apm-aws-lambda/apm-lambda-extension/extension/http_server_test.go:239 +0x3fa
 
 ```
</p></details>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/library%2Fapm-aws-lambda-mbp%2FPR-208/detail/PR-208/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Running Go tests`
<ul>
<li>Took 2 min 42 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/library/pipelines/apm-aws-lambda-mbp/pipelines/PR-208/runs/1/steps/345/log/?start=0">here</a></li>
<li>Description: <code>gotestsum --format testname --junitfile junit-report.xml -- -v ./...</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-06-03 14:44 UTC, stuartnelson3 commented on apm-lambda-extension/extension/process_env.go
> +	"encoding/base64"
is there any sort of linting for import order? other projects separate out stdlib / elastic / 3rd party

2022-06-03 14:45 UTC, stuartnelson3 commented on apm-lambda-extension/extension/process_env.go
> +	region := os.Getenv("AWS_REGION")
might want to check region != "" and return a descriptive error

2022-06-03 14:46 UTC, stuartnelson3 commented on apm-lambda-extension/extension/process_env.go
> +		len, err := base64.StdEncoding.Decode(decodedBinarySecretBytes, result.SecretBinary)
`len` is a builtin and, while the compiler might let you use it, it'd probably be better to choose a different variable name

2022-06-03 14:53 UTC, stuartnelson3 commented on apm-lambda-extension/extension/process_env.go
> +		} else {
same as above

2022-06-03 15:09 UTC, simitt commented
@elastic/apm-server could you please help pushing this over the finish line; I suggest for this PR rather than only reviewing, commit small code improvements directly to free up @AlexanderWert. 
Thanks Alex for this contribution.

2022-06-07 16:33 UTC, jlvoiseux requested changes
LGTM, aside from the small test correction.
I was also able to get the PR to work end-to-end by following the repro steps.

2022-06-07 16:33 UTC, jlvoiseux commented on apm-lambda-extension/extension/process_env_test.go
> +func TestGetSecretCalled(t *testing.T) {
It seems that the Unit test, when run sequentially together with the whole test suite, fails due to previously set values of the `SECRET_TOKEN` and the `API_KEY`.
```suggestion
func TestGetSecretCalled(t *testing.T) {
    os.Clearenv()
```

2022-06-08 05:53 UTC, merged